const state={recipes:[],route:'home',history:[]};
const view=document.querySelector('#view'),title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),backBtn=document.querySelector('#backBtn');

const normalize=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function readRecipes(raw){if(Array.isArray(raw))return raw;if(Array.isArray(raw.receitas))return raw.receitas;if(Array.isArray(raw.recipes))return raw.recipes;return []}
function getField(r,...names){for(const n of names){if(r?.[n]!=null&&r[n]!=='')return r[n]}return ''}
function recipeName(r){return getField(r,'nome','name','receita')||getField(r,'id','codigo')}
function recipeId(r){return getField(r,'codigo','id','recipe_id','receita_id')}
const recipeImages=new Set(['RC0001','RC0002','RC0003','RC0004','RC0005']);
function recipeImage(r){const id=String(recipeId(r));return recipeImages.has(id)?`images/recipes/${id}.webp`:''}
function category(r){return getField(r,'categoria','category')||'Outras'}
function time(r){const v=getField(r,'tempo','tempo_total','tempo_minutos','time_minutes','time');return typeof v==='number'?`${v} min`:v}
function servings(r){return getField(r,'rendimento','porcoes','porções','servings')}
function difficulty(r){return getField(r,'dificuldade','difficulty')}
function instructions(r){const v=getField(r,'modo_preparo','modo de preparo','preparo','instrucoes','instruções','instructions','steps');return Array.isArray(v)?v.map((x,i)=>`${i+1}. ${x}`).join('\n\n'):v}
function ingredients(r){const list=getField(r,'ingredientes','ingredients');if(Array.isArray(list))return list.map(i=>typeof i==='string'?i:[getField(i,'quantidade','quantity'),getField(i,'unidade','unit'),getField(i,'nome','ingrediente','name'),getField(i,'observacao','observação','preparo','preparation','note')].filter(Boolean).join(' '));return typeof list==='string'?list.split(/\n|;/).filter(Boolean):[]}
function card(r){const img=recipeImage(r);return `<button class="recipe-card" data-recipe="${esc(recipeId(r))}">${img?`<img class="recipe-card-image" src="${img}" alt="${esc(recipeName(r))}" loading="lazy">`:''}<h3>${esc(recipeName(r))}</h3><div class="meta"><span>${esc(category(r))}</span>${time(r)?`<span>⏱ ${esc(time(r))}</span>`:''}${difficulty(r)?`<span>• ${esc(difficulty(r))}</span>`:''}</div></button>`}
function setHeader(t,sub='',back=false){title.textContent=t;subtitle.textContent=sub;backBtn.classList.toggle('is-hidden',!back)}
function setActive(route){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
function home(){setHeader('Menu de Casa','O que tem em casa vira receita');setActive('home');const featured=state.recipes.slice(0,6);view.innerHTML=`<section class="hero"><h1>O que vamos cozinhar hoje?</h1><p>Explore receitas de casa agora. Em breve, você poderá informar seus ingredientes e encontrar receitas adaptadas ao que tem disponível.</p></section><section class="quick-grid"><button class="quick-card" data-route="recipes"><b>🍲 Receitas</b><small>Veja as ${state.recipes.length} receitas da base inicial.</small></button><button class="quick-card" data-route="categories"><b>🥗 Categorias</b><small>Escolha pelo tipo de prato.</small></button><button class="quick-card" data-route="search"><b>🔎 Buscar</b><small>Procure uma receita pelo nome.</small></button><button class="quick-card emphasis" disabled><b>🏠 Tenho em casa</b><small>Função inteligente preparada para uma próxima versão.</small></button></section><div class="section-title"><h2>Para começar</h2><button data-route="recipes">Ver todas</button></div><section class="recipe-list">${featured.map(card).join('')}</section>`}
function recipes(){setHeader('Receitas',`${state.recipes.length} receitas disponíveis`);setActive('recipes');view.innerHTML=`<input class="searchbox" id="recipeFilter" placeholder="Filtrar receitas..." autocomplete="off"><section id="recipeResults" class="recipe-list">${state.recipes.map(card).join('')}</section>`;document.querySelector('#recipeFilter').addEventListener('input',e=>{const q=normalize(e.target.value);document.querySelector('#recipeResults').innerHTML=state.recipes.filter(r=>normalize(recipeName(r)).includes(q)||normalize(category(r)).includes(q)).map(card).join('')||'<div class="empty">Nenhuma receita encontrada.</div>'})}
function categories(){setHeader('Categorias','Escolha um tipo de receita');setActive('categories');const map=new Map();state.recipes.forEach(r=>map.set(category(r),(map.get(category(r))||0)+1));view.innerHTML=`<section class="category-grid">${[...map.entries()].sort().map(([c,n])=>`<button class="category-card" data-category="${esc(c)}"><strong>${esc(c)}</strong><span>${n} receita${n!==1?'s':''}</span></button>`).join('')}</section>`}
function categoryRecipes(c){setHeader(c,'Receitas desta categoria',true);setActive('categories');const rs=state.recipes.filter(r=>category(r)===c);view.innerHTML=`<section class="recipe-list">${rs.map(card).join('')}</section>`}
function search(){setHeader('Buscar','Encontre uma receita');setActive('search');view.innerHTML=`<input class="searchbox" id="globalSearch" placeholder="Digite o nome ou categoria..." autocomplete="off" autofocus><section id="searchResults"><div class="empty">Comece digitando para pesquisar.</div></section>`;document.querySelector('#globalSearch').addEventListener('input',e=>{const q=normalize(e.target.value.trim());const rs=q?state.recipes.filter(r=>normalize(recipeName(r)).includes(q)||normalize(category(r)).includes(q)):[];document.querySelector('#searchResults').innerHTML=rs.length?`<div class="recipe-list">${rs.map(card).join('')}</div>`:'<div class="empty">Nenhuma receita encontrada.</div>'})}
function detail(id){const r=state.recipes.find(x=>String(recipeId(x))===String(id));if(!r)return;setHeader('Receita',recipeId(r),true);document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));const ing=ingredients(r),img=recipeImage(r);view.innerHTML=`<article class="detail">${img?`<img class="recipe-hero-image" src="${img}" alt="${esc(recipeName(r))}">`:''}<span class="pill">${esc(category(r))}</span><h1>${esc(recipeName(r))}</h1><div class="meta">${time(r)?`<span>⏱ ${esc(time(r))}</span>`:''}${servings(r)?`<span>🍽 ${esc(servings(r))}</span>`:''}${difficulty(r)?`<span>★ ${esc(difficulty(r))}</span>`:''}</div><section class="detail-box"><h2>Ingredientes</h2>${ing.length?`<ul class="ingredients">${ing.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:'<p>Ingredientes cadastrados na base.</p>'}</section><section class="detail-box"><h2>Modo de preparo</h2><p class="steps">${esc(instructions(r)||'Modo de preparo cadastrado na base de receitas.')}</p></section></article>`}
function navigate(route,arg,push=true){if(push&&state.route!==route)state.history.push({route:state.route});state.route=route;if(route==='home')home();if(route==='recipes')recipes();if(route==='categories')categories();if(route==='category')categoryRecipes(arg);if(route==='search')search();if(route==='detail')detail(arg);window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',e=>{const route=e.target.closest('[data-route]');if(route)navigate(route.dataset.route);const rc=e.target.closest('[data-recipe]');if(rc)navigate('detail',rc.dataset.recipe);const cc=e.target.closest('[data-category]');if(cc)navigate('category',cc.dataset.category)});
backBtn.addEventListener('click',()=>{const prev=state.history.pop();navigate(prev?.route||'home',null,false)});
async function init(){try{const files=['01','02','03','04','05','06'];const blocks=await Promise.all(files.map(async n=>{const res=await fetch(`data/receitas-${n}.json`);if(!res.ok)throw new Error(`Falha no bloco ${n}`);return readRecipes(await res.json())}));state.recipes=blocks.flat().sort((a,b)=>String(recipeId(a)).localeCompare(String(recipeId(b))));}catch(e){console.error(e);view.innerHTML='<div class="empty">Não foi possível carregar as receitas.</div>'}setTimeout(()=>{document.querySelector('#splash').style.opacity='0';setTimeout(()=>{document.querySelector('#splash').remove();document.querySelector('#app').classList.remove('is-hidden');home()},350)},900);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
init();
